# Generated by Django 6.0.5 on 2026-05-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant'),
    ]

    operations = [
    ]
